module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-normal",
    "bg-fire",
    "bg-water",
    "bg-grass",
    "bg-electric",
    "bg-ice",
    "bg-fighting",
    "bg-poison",
    "bg-ground",
    "bg-flying",
    "bg-psychic",
    "bg-bug",
    "bg-rock",
    "bg-ghost",
    "bg-dark",
    "bg-dragon",
    "bg-steel",
    "bg-fairy",
    "from-normal",
    "from-fire",
    "from-water",
    "from-grass",
    "from-electric",
    "from-ice",
    "from-fighting",
    "from-poison",
    "from-ground",
    "from-flying",
    "from-psychic",
    "from-bug",
    "from-rock",
    "from-ghost",
    "from-dark",
    "from-dragon",
    "from-steel",
    "from-fairy",
    "to-green-400",
    "to-gray-800",
    "to-purple-800",
    "to-yellow-400",
    "to-pink-400",
    "to-red-900",
    "to-red-400",
    "to-indigo-600",
    "to-indigo-700",
    "to-green-600",
    "to-yellow-700",
    "to-blue-400",
    "to-gray-500",
    "to-purple-600",
    "to-pink-700",
    "to-yellow-600",
    "to-gray-400",
    "to-blue-500",
  ],
  theme: {
    extend: {
      fontFamily: {
        inter: ["inter", "sans-serif"],
      },
      colors: {
        normal: "#a8a877",
        fire: "#ef8030",
        water: "#6790f0",
        grass: "#78c84f",
        electric: "#f8cf30",
        ice: "#98d8d8",
        fighting: "#c03028",
        poison: "#9f409f",
        ground: "#E0C068",
        flying: "#A890F0",
        psychic: "#F85787",
        bug: "#A8B720",
        rock: "#B8A038",
        ghost: "#6F5898",
        dark: "#6F5848",
        dragon: "#7038F8",
        steel: "#B8B8D0",
        fairy: "#F0B5BC",
      },
    },
  },
  plugins: [require("prettier-plugin-tailwindcss")],
};
